%% SpringApplicationTests.shouldStartDaemonThreadIfKeepAliveIsEnabled() -> SpringApplication.run(1 param)
sequenceDiagram
    actor Entry
    participant SpringApplicationTests
    participant SpringApplication
    Note over Entry: ⚠ No callers found (possible dead code)
    Entry->>SpringApplicationTests: shouldStartDaemonThreadIfKeepAliveIsEnabled()
    SpringApplicationTests->>SpringApplication: run(String)
