%% ConfigDataEnvironmentPostProcessorIntegrationTests.loadWhenHasConfigLocationAsFile() -> SpringApplication.run(1 param)
sequenceDiagram
    actor Entry
    participant ConfigDataEnvironmentPostProcessorIntegrationTests
    participant SpringApplication
    Note over Entry: ⚠ No callers found (possible dead code)
    Entry->>ConfigDataEnvironmentPostProcessorIntegrationTests: loadWhenHasConfigLocationAsFile()
    ConfigDataEnvironmentPostProcessorIntegrationTests->>SpringApplication: run(String)
