%% ConfigDataEnvironmentPostProcessorImportCombinedWithProfileSpecificIntegrationTests.testWithProfile() -> SpringApplication.run(1 param)
sequenceDiagram
    actor Entry
    participant ConfigDataEnvironmentPostProcessorImportCombinedWithProfileSpecificIntegrationTests
    participant SpringApplication
    Note over Entry: ⚠ No callers found (possible dead code)
    Entry->>ConfigDataEnvironmentPostProcessorImportCombinedWithProfileSpecificIntegrationTests: testWithProfile()
    ConfigDataEnvironmentPostProcessorImportCombinedWithProfileSpecificIntegrationTests->>SpringApplication: run(String)
