%% SpringBootServletInitializerTests.servletContextPropertySourceIsAvailablePriorToRefresh() -> SpringBootServletInitializer.createRootApplicationContext(1 param) -> SpringApplicationBuilder.build() -> SpringApplicationBuilder.build(1 param) -> SpringApplicationBuilder.configureAsChildIfNecessary(1 param) -> SpringApplicationBuilder.run(1 param) -> SpringApplication.run(1 param)
sequenceDiagram
    actor Entry
    participant SpringBootServletInitializerTests
    participant SpringBootServletInitializer
    participant SpringApplicationBuilder
    participant SpringApplication
    Note over Entry: ⚠ No callers found (possible dead code)
    Entry->>SpringBootServletInitializerTests: servletContextPropertySourceIsAvailablePriorToRefresh()
    SpringBootServletInitializerTests->>SpringBootServletInitializer: createRootApplicationContext(ServletContext)
    SpringBootServletInitializer->>SpringApplicationBuilder: build()
    SpringApplicationBuilder->>SpringApplicationBuilder: build(String)
    SpringApplicationBuilder->>SpringApplicationBuilder: configureAsChildIfNecessary(String)
    SpringApplicationBuilder->>SpringApplicationBuilder: run(String)
    SpringApplicationBuilder->>SpringApplication: run(String)
