%% ConfigDataEnvironmentPostProcessorBootstrapContextIntegrationTests.bootstrapsApplicationContext() -> SpringApplication.run(1 param)
sequenceDiagram
    actor Entry
    participant ConfigDataEnvironmentPostProcessorBootstrapContextIntegrationTests
    participant SpringApplication
    Note over Entry: ⚠ No callers found (possible dead code)
    Entry->>ConfigDataEnvironmentPostProcessorBootstrapContextIntegrationTests: bootstrapsApplicationContext()
    ConfigDataEnvironmentPostProcessorBootstrapContextIntegrationTests->>SpringApplication: run(String)
