%% SpringApplicationTests.defaultPropertiesShouldBeMerged() -> SpringApplicationBuilder.build() -> SpringApplicationBuilder.build(1 param) -> SpringApplicationBuilder.configureAsChildIfNecessary(1 param) -> SpringApplicationBuilder.run(1 param) -> SpringApplication.run(1 param)
sequenceDiagram
    actor Entry
    participant SpringApplicationTests
    participant SpringApplicationBuilder
    participant SpringApplication
    Note over Entry: ⚠ No callers found (possible dead code)
    Entry->>SpringApplicationTests: defaultPropertiesShouldBeMerged()
    SpringApplicationTests->>SpringApplicationBuilder: build()
    SpringApplicationBuilder->>SpringApplicationBuilder: build(String)
    SpringApplicationBuilder->>SpringApplicationBuilder: configureAsChildIfNecessary(String)
    SpringApplicationBuilder->>SpringApplicationBuilder: run(String)
    SpringApplicationBuilder->>SpringApplication: run(String)
