package com.jsrc.app.spec;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Parses a Markdown spec file into structured data for verification.
 * Expects format generated by --context --md.
 */
public class SpecParser {

    private static final Logger logger = LoggerFactory.getLogger(SpecParser.class);

    /**
     * A method defined in the spec.
     */
    public record SpecMethod(
            String name,
            String signature,
            List<String> expectedThrows,
            List<String> expectedAnnotations
    ) {}

    /**
     * Parsed spec.
     */
    public record Spec(
            String className,
            List<SpecMethod> methods
    ) {}

    /**
     * Parses a Markdown spec file.
     */
    public static Spec parse(Path specFile) throws IOException {
        List<String> lines = Files.readAllLines(specFile);
        String className = "";
        List<SpecMethod> methods = new ArrayList<>();

        String currentMethodSig = "";
        List<String> currentThrows = new ArrayList<>();
        List<String> currentAnnotations = new ArrayList<>();
        boolean inMethods = false;

        for (String line : lines) {
            String trimmed = line.trim();

            // # ClassName
            if (trimmed.startsWith("# ") && className.isEmpty()) {
                className = trimmed.substring(2).trim();
                continue;
            }

            // Track sections
            if (trimmed.startsWith("## ")) {
                inMethods = trimmed.startsWith("## Methods");
            }

            // ### methodSignature  or  - `methodSignature`
            String methodSig = null;
            if (trimmed.startsWith("### ")) {
                methodSig = trimmed.substring(4).trim();
            } else if (trimmed.startsWith("- `") && trimmed.endsWith("`") && inMethods) {
                methodSig = trimmed.substring(3, trimmed.length() - 1).trim();
            }
            if (methodSig != null) {
                // Flush previous method
                flushMethod(methods, currentMethodSig, currentThrows, currentAnnotations);
                currentMethodSig = methodSig;
                currentThrows = new ArrayList<>();
                currentAnnotations = new ArrayList<>();
                continue;
            }

            // - **Throws:** IOException, IllegalStateException (tolerant: Throws/throws, with/without colon)
            if (trimmed.toLowerCase().startsWith("- **throws**") || trimmed.toLowerCase().startsWith("- **throws:**")) {
                int idx = trimmed.indexOf("**", 4);
                String throwsStr = (idx >= 0) ? trimmed.substring(idx + 2).trim() : "";
                if (throwsStr.startsWith(":")) throwsStr = throwsStr.substring(1).trim();
                for (String t : throwsStr.split(",")) {
                    String ex = t.trim();
                    if (!ex.isEmpty()) currentThrows.add(ex);
                }
                continue;
            }

            // - **Annotation:** @Override (tolerant: Annotation/annotation, with/without colon)
            if (trimmed.toLowerCase().startsWith("- **annotation**") || trimmed.toLowerCase().startsWith("- **annotation:**")) {
                int idx = trimmed.indexOf("**", 4);
                String ann = (idx >= 0) ? trimmed.substring(idx + 2).trim() : "";
                if (ann.startsWith(":")) ann = ann.substring(1).trim();
                if (ann.startsWith("@")) ann = ann.substring(1);
                if (!ann.isEmpty()) currentAnnotations.add(ann);
                continue;
            }
        }

        // Flush last method
        flushMethod(methods, currentMethodSig, currentThrows, currentAnnotations);

        logger.info("Parsed spec '{}': {} methods", className, methods.size());
        return new Spec(className, methods);
    }

    private static void flushMethod(List<SpecMethod> methods, String sig,
                                     List<String> thrw, List<String> anns) {
        if (sig.isEmpty()) return;
        // Extract method name from signature
        String name = extractMethodName(sig);
        methods.add(new SpecMethod(name, sig, List.copyOf(thrw), List.copyOf(anns)));
    }

    private static String extractMethodName(String signature) {
        // "public void create(String name)" → "create"
        int parenIdx = signature.indexOf('(');
        if (parenIdx < 0) return signature;
        String beforeParen = signature.substring(0, parenIdx).trim();
        int lastSpace = beforeParen.lastIndexOf(' ');
        return lastSpace >= 0 ? beforeParen.substring(lastSpace + 1) : beforeParen;
    }
}
